### ISSUE TITLE
Als KCM wil ik bepaalde (meta)data vastleggen bij het contactmoment

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#111]
### Toelichting
Bepaalde (meta)data automatisch koppelen (zoals bijvoorbeeld tijdsduur of afhandeltijd van het gesprek, chat, WhatsApp, etc.) aan vraagregistratie, zodat dit later in rapportages kan worden gebruikt. 

**Vragen aan gebruikersgroep**
- Naar aanleiding van  comment van Hanneke, wat wordt bedoeld met 'status' (is dat zelfde als gespreksresultaat)
> *Antwoord 14/07/2022*: ja: status = gespreksresultaat
-  en hoe bepalen we de 'Vraagcategorie' 
> *Antwoord*: In de VNG-documentatie staat 'Onderwerplinks' als een lijst met links. 
- is het de bedoeling dat we ook voorzien in het tonen/exporteren van management informatie?
> Besproken 14/07/2022Het maken van (management)rapportages gebeurt NIET binnen KISS, maar vanuit het systeem waarin de contactmomenten worden geregistreerd.

**Besproken in Ontwerpgroep 01/09/2022:**
Met uitzondering van starttijd en eindtijd slaan we alleen meta-data op waarvoor de Standaard een Property heeft. Dit betekent dat rapportages ook alleen over die eigenschappen van Contactmomenten kunnen worden gemaakt. 

Voor deze story maken we de volgende uitbreidingen op het Contactmoment: 
- starttijd toevoegen
- eindtijd toevoegen

### Acceptatiecriteria
- [x] start-/eindtijd automatisch opslaan bij elk contactmoment. Nb. op dit moment is dat de enige beschikbare metadata die nog niet opgeslagen wordt bij het contactmoment. en dus het enige acceptatie criterium voor deze story.
    - Startdatum = datum+ tijd waarop je op Start Contactmoment klikt
    - Einddatum = datum+tijd waarop je het Contactmoment opslaat; dit is dus dezelfde datum/tijd als registratiedatum/tijd. 
- [x] ~Zorgen dat startijd getoond wordt bij dat Contactmoment in het Klantbeeld.~ _SH02/09: dit is nu niet nodig. We tonen alleen de datum, en bij telefonie en baliecontacten zal die voor alle drie de datum/tijdstippen hetzelfde zijn. Tegen de tijd dat we contactmoment krijgen de op een dag ná de datum van starten, afgerond worden, besluiten we wat we daar mee doen._

### Functionele teststappen
- [ ] Start een contactmoment en klik enige tijd rond
- [ ] Sla het contactmoment op, en controleer in Developertools > Network-tab of alle drie de tijdstippen juist zijn gevuld.

### Taken Conduction
- [ ] ...
- [ ] ...

### Taken ICATT
- [x] start- en eindtijd meesturen met contactmoment (daar zijn al velden voor, zie comment ruben). 
starttijd is het moment dat je op 'start contactmoment' klikt. eindtijd is het moment dat je het contactmoment-afhandel-formulier opslaat (dus niet als je op de knop 'einde contactmoment' drukt)
- [x] ~starttijd ook tonen bij de eerdere contactmomenten  bij het klantbeeld~

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

## Taken Conduction
- [ ] In gateway bijhouden welke objecten in een sessie zijn bekeken
- [ ] Deze via een API bevaarbaar maken

**Comment by rubenvdlinde** [comment]
Voor mij is het hierbij van belang dat we een overzicht krijgen van welke metadata we willen verzamelen en waaraan deze automatisch moet worden gekoppeld.

**Comment by rubenvdlinde** [comment]
Ik zie hier in de praktijk nog wel wat problemen in hoe we dit uit elkaar gaan trekken. defacto betekend het dat je binnen een contact moment een onderverdeling in vragen gaat maken en dan per vraag wat gaat bijhouden. Dat leid tot een best wel diepe en onoverzichtelijke stapeling van objecten.

Ik zou dan eerder geneigd zijn om te zeggen een contact moment is één vraag en contact momenten zijn te clusteren in gesprekken. In dat geval valt de metadata van het contact moment en de vraag samen. Slaan we dingen maar een keer op en is er een overzichtenlijkere dataset beschikbaar voor rapportages.

**Comment by sytskevanhasselt** [comment]
Ik had aangegeven dat in de interface Starttijd niet getoond hoefde te worden. 
Maar: ik had me niet gerealiseerd dat er ook echt een TIJD getoond wordt, ik dacht dat het alleen een datum was. 
Nu liggen die tijden binnen onze tests niet heel veel uit elkaar. En ik weet eigenlijk niet WE gaan bij de gebruikersgroep navragen of dit preciezer moet.

**Comment by sytskevanhasselt** [comment]
Status = Done
