### ISSUE TITLE
Als beheerder van de inhoud van het startscherm wil ik nieuwsitems en werkinstructies maken, prioriteren, aanpassen en verwijderen

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#17]
zodat de content voortdurend up-to-date is.

**Projectcode**: B-01

### Toelichting
De statische lijsten met werkinstructies en nieuwsberichten van story A-01 #16  worden dynamisch gemaakt door ze te koppelen aan een bron.
Dit betreft een interne KISS bron. Hiervoor mag een CMS gebruikt worden. Hoeft niet.
In omschrijving wordt gesuggereerd dat de redacteur zelf de prioriteit kan aangeven van de berichten. er is afgesproken vooralsnog alleen automatisch te prioriteren op datum. 

we bekijken of OpenPub gebruikt kan worden (alleen gebruiken als we erop vertrouwen dat de andere A en B stories daar ook mee gerealiseerd kunnen worden).

### Acceptatiecriteria
- [x] Een redacteur moet vanuit KISS naar de beheeromgeving kunnen navigeren.

Het is acceptabel als de beheerschermen niet geïntegreerd zijn in KISS en dat de redacteur de content rechtstreeks in een CMS beheerd, maar dan moet de authenticatie wel geïntegreerd zijn met KISS. Het mag niet zo zijn dat de redacteur apart moet inloggen in het CMS. NB. er is nog helemaal geen autorisatie, maar vooruitlopend daarop moet er wel al rekening gehouden worden bij het kiezen een technische oplossing.

- [x] een redacteur kan berichten toevoegen, aanpassen en verwijderen.
- [x] een bericht bestaat uit een kop, tekst en een datum. De datum wordt automatisch gevuld/bijgewerkt bij aanmaken/wijzigen
- [x] nieuwste/laatst bijgewerkte berichten komen bovenaan.
- [x] aangezien de medewerkers vaak langere tijd het scherm open hebben staan, moeten alle wijzigingen realtime naar de browser gepushd worden.
- [x] De data wordt getoond in de werkinstructies en nieuwsfeed van story A-01 #16 
- [x] berichten verschijnen direct (nog geen publicatie datum oid)
- [x] Er zijn nog geen rollen. iedereen is voorlopig redacteur.

### Functionele teststappen
1. Test met twee schermen: inlogggen op de beheeromgeving. Voer 3 nieuwsberichten in, voer 2 werkinstructies in
2. Tweede scherm/browser: Andere gebruiker opent KISS: Andere gebruiker ziet twee lijstjes, waarbij de laatst toegevoegde items bovenaan staan.
3. Als beheerder: wijzig het tweede nieuwsbericht. Andere gebruiker ziet de lijst nieuwsberichten wijzigen: het aangepaste bericht komt bovenaan te staan, met de gewijzigde tekst. 
4. Als beheerder: voeg een derde werkinstructie toe. Andere gebruiker ziet de nieuwe werkinstructie bovenin de lijst verschijnen.
5. Als beheerder: voeg in totaal meer dan 10 nieuwberichten en werkinstructies in: Andere gebruiker ziet paginering die correct werkt

**BEVINDINGEN**
- [x] paginering werkt niet goed dubbele nummers, niet klikbaar op nummers
- [x] Link naar editor ontbreekt nog https://openweb.kiss-dev.commonground.nu/wp-login.php

### Taken Conduction
- [ ] Installatie van PUB (reeds ingeschat onder #23)
- [ ] Basale inrichting PUB inc voorbeeld werkinstructies (reeds ingeschat onder #16)
- [x] #47
- [ ] Admin UI
- [ ] Admin UI uitleg
- [ ] Toevoegen testdata in Admin UI
- [ ] #70

### Tijdinschatting 
- *Conduction* 16
- *ICATT* 2 (ervan uitgaande dat het beheer rechtstreeks in het cms zal plaatsvinden)

**Comment by rubenvdlinde** [comment]
Voornaamste hier is dat we de PUB api zullen moeten uitbreiden, dat is niet bepaald een probleem (eerder een commonground doel) maar daar moeten we dan wel de uren voor reserveren.

**Comment by rubenvdlinde** [comment]
n.b. We gaan dus alleen de GET API implementeren, het aanmaken en beheren van nieuwsberichten vind plaats in Open Webconcept wordpress gothenburg)

**Comment by felixcicatt** [comment]
TODO ICATT:
- splitsen tussen werkinstructies en nieuws (hoe?)
- aansluiten op updates (via WebSockets?)

**Comment by PascalIcatt** [comment]
localhost/hostname variabel instelbaar maken bij deployments

**Comment by felixcicatt** [comment]
@hannekevanderhorst De bevindingen zijn nu als het goed is opgelost.

**Comment by sytskevanhasselt** [comment]
Status = done
