### ISSUE TITLE
Als gebruiker wil ik dat een aantal bekende bugs zijn opgelost (Put/Patch redoc bijwerken, gedaan?)

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#372]
### Taken Conduction

- [x] #245
- [x] #226
- [x] Low prio: #386 
- [x] #255 >> WIE moet dit testen?
- [x] #367 >> update SH22/11: lastig testen
- [x] #411  >> update SH22/11: nog niet goed m.i.
- [x] #338
- [x] #380 
- [x] #231 >> verplaatst naar Technical Debt
- [x] #233 
- [x] #394

**Comment by WilcoLouwerse** [comment]
@rjzondervan 
#338
#255
#266
#231
#233

@WilcoLouwerse 
#245
#367

**Comment by rjzondervan** [comment]
#255 is naar testing voor DEV

**Comment by felixcicatt** [comment]
@rubenvdlinde #380

**Comment by WilcoLouwerse** [comment]
#255 afgetest, kleine fix gedaan maar verder in orde

**Comment by sytskevanhasselt** [comment]
NB: #380 is nog NIET opgelost. Zie onderstaand screenshot. Ik zie dit resultaat zowel op kiss-dev.commonground (ACC) als op kissdevelopment-frontend.commonground (DEV)


![Image](https://user-images.githubusercontent.com/53014699/202496841-34e300d1-6873-4017-b539-719fce150e2f.png)

**Comment by sytskevanhasselt** [comment]
@WilcoLouwerse; @rjzondervan : #411 is nog niet goed m.i.

**Comment by sytskevanhasselt** [comment]
#367 is momenteel lastig testen. Op ACC ziet alles er goed uit. 
Lencodes heeft een aanpassing op DEV gedeployed. Maar de hele sortering op dev is niet goed, dus moeilijk testen.

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
